-- 1. 전지연 사원이 속해있는 부서원들을 조회하시오 (단, 전지연은 제외)
-- 사번, 사원명, 전화번호, 고용일, 부서명

SELECT EMP_ID, EMP_NAME, PHONE, HIRE_DATE, DEPT_TITLE
FROM EMPLOYEE 
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE
				   WHERE EMP_NAME = '전지연')
AND EMP_NAME != '전지연';



SELECT EMP_ID, EMP_NAME, JOB_NAME,
    FLOOR (MONTHS_BETWEEN(SYSDATE, TO_DATE( SUBSTR(EMP_NO, 1, 6), 'RRMMDD') ) / 12) "만 나이",
    TO_CHAR(  SALARY * (1 + NVL(BONUS, 0))  * 12 , 'L999,999,999') "보너스 포함 연봉"
FROM EMPLOYEE E1 
JOIN JOB J ON( E1.JOB_CODE = J.JOB_CODE )
WHERE SUBSTR(EMP_NO, 1, 6)
    = (SELECT MAX(SUBSTR(EMP_NO, 1, 6))
        FROM EMPLOYEE E2
        WHERE E2.JOB_CODE = E1.JOB_CODE)
ORDER BY "만 나이" DESC;



